CREATE TABLE "etl_load_drvr" (
  "etl_load_drvr_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "source" varchar,
  "target" varchar,
  "src_database_meta_data" json,
  "tgt_database_meta_data" json,
  "src_table_info" json,
  "tgt_table_info" json,
  "src_file_metadata" json,
  "tgt_file_metadata" json,
  "dq_screen_id" varchar,
  "rec_ins_ts" timestamp
);

CREATE TABLE "audit_log" (
  "audit_log_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "etl_load_drvr_key" varchar,
  "process_name" varchar,
  "start_time" timestamp,
  "end_time" timestamp,
  "impact_object" varchar,
  "status" varchar
);

CREATE TABLE "screen" (
  "screen_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "screen_name" varchar,
  "screen_ds" varchar,
  "filename" varchar,
  "error_bucket" json,
  "email" varchar,
  "rec_ins_ts" timestamp
);

CREATE TABLE "dq_rules" (
  "rule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rule_name" varchar,
  "rule_ds" varchar,
  "screen_id" integer,
  "rule_type" varchar,
  "rule_query" varchar,
  "rec_ins_ts" timestamp
);

CREATE TABLE "dq_row_alert_log" (
  "row_alert_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scr_run_key" int,
  "rule_id" integer,
  "rule_ds" varchar,
  "error_record_count" integer,
  "rec_ins_ts" timestamp
);

CREATE TABLE "dq_profile_alert_log" (
  "profile_alert_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rule_id" integer,
  "scr_run_key" int,
  "rule_ds" varchar,
  "error_record_count" integer,
  "rec_ins_ts" timestamp
);

CREATE TABLE "dq_scr_run_log" (
  "scr_run_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "screen_id" integer,
  "start_time" timestamp,
  "end_time" timestamp,
  "status" varchar,
  "error_msg" varchar,
  "rec_ins_ts" timestamp
);

ALTER TABLE "etl_load_drvr" ADD FOREIGN KEY ("etl_load_drvr_key") REFERENCES "audit_log" ("etl_load_drvr_key");

ALTER TABLE "etl_load_drvr" ADD FOREIGN KEY ("dq_screen_id") REFERENCES "screen" ("screen_id");

ALTER TABLE "dq_rules" ADD FOREIGN KEY ("screen_id") REFERENCES "screen" ("screen_id");

ALTER TABLE "dq_row_alert_log" ADD FOREIGN KEY ("scr_run_key") REFERENCES "dq_scr_run_log" ("scr_run_key");

ALTER TABLE "dq_row_alert_log" ADD FOREIGN KEY ("rule_id") REFERENCES "dq_rules" ("rule_id");

ALTER TABLE "dq_scr_run_log" ADD FOREIGN KEY ("screen_id") REFERENCES "screen" ("screen_id");

ALTER TABLE "dq_profile_alert_log" ADD FOREIGN KEY ("scr_run_key") REFERENCES "dq_scr_run_log" ("scr_run_key");

ALTER TABLE "dq_profile_alert_log" ADD FOREIGN KEY ("rule_id") REFERENCES "dq_rules" ("rule_id");
